name: Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: novel_on_web/.nvmrc
          cache: yarn
          cache-dependency-path: novel_on_web/yarn.lock

      - name: Install
        run: yarn --cwd novel_on_web install --frozen-lockfile

      - name: Build
        run: yarn --cwd novel_on_web build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: novel_on_web/dist
          retention-days: 1

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
